from typing import List, Optional, Callable
from typing_extensions import TypedDict
from langchain.schema import Document


class GraphState(TypedDict):
    """
    Represents the state of the LangGraph workflow for RAG.

    Attributes:
        question (str): User's input question.
        web_search_query (str): Query used for web searches if needed.
        generation (str): The final answer generated by the LLM.
        search (str): Indicator to determine if a web search is required ("Yes" or "No").
        documents (List[Document]): List of retrieved or web-searched documents.
        steps (List[str]): List of processing steps already completed.
        retriever (Optional[Callable]): The document retriever used for fetching information.
    """

    question: str
    web_search_query: str
    generation: str
    search: str  # Expected values: "Yes" or "No"
    documents: List[Document]
    steps: List[str]
    retriever: Optional[Callable]  # More explicit than Any
